spring:
  datasource:
    url: jdbc:h2:file:./data/demo2-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


app:
  api:
    endpoints:
      user: # USER ENDPOINTS
        base-url: /api/v1/user
        apis:
          create-new-user:
          get-user-by-id: /{userId}
          login: /login

      course: # COURSE ENDPOINTS
        base-url: /api/v1
        apis:
          create-new-course: /course
          get-course-by-id: /course/{courseId}
          get-courses-by-category: /courses
          delete-all-courses: /courses
          get-my-courses: /courses/my-learning
          get-my-fav: /courses/favourites
          add-fav-course: /courses/{courseId}/favourites
      cart: # CART ENDPOINTS
        base-url: /api/v1/carts
        apis:
          get-cart: /{userId}
          add-to-cart: /course/{courseId}
          remove-from-cart: /{itemId}
          buy-now: /buy


jwt:
  secret-key: my_super_secret_key_which_is_32+_chars
  expiration-ms: 7200000